service: demo
frameworkVersion: '3'

custom: 
  settings:
    ACCOUNT_ID: "581086713195"
    DYNAMODB_DLQ_TABLE: ${self:service}-dlqlist-${sls:stage}

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment: ${self:custom.settings}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: "arn:aws:sqs:${self:provider.region}:*:demo"
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

constructs:
  jobs:
    type: queue
    worker:
      handler: handler.consumer


functions:
  producer:
    handler: Produce.producer
    events:
      - httpApi:
          method: get
          path: /produce
    environment:
      QUEUE_URL: ${construct:jobs.queueUrl}
  consume:
    handler: Consume.consumer
    events:
      - sqs:
          arn: 
            Fn::GetAtt:
              - demo
              - Arn
          batchSize: 10
  saveDLQ:
    handler: DlqList.savedata
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - dlqlist
              - Arn

plugins:
  - serverless-lift

resources: 
  Resources: 
    demo:
      Type: "AWS::SQS::Queue"
      Properties:
        RedrivePolicy:
          deadLetterTargetArn: arn:aws:sqs:us-east-1:581086713195:demodlq
          maxReceiveCount: 3
        QueueName: "demo"
    
    demodlq:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "demodlq"
    
    dlqlist: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-dlqlist-${sls:stage}
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
