service: demo
frameworkVersion: '3'

custom: 
  settings:
    ACCOUNT_ID: "581086713195"
    DYNAMODB_DLQ_TABLE: ${self:service}-dlqlist-${sls:stage}

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment: ${self:custom.settings}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource: "*"

constructs:
  jobs:
    type: queue
    worker:
      handler: handler.consumer


functions:
  producer:
    handler: Produce.producer
    events:
      - httpApi:
          method: get
          path: /produce
    environment:
      QUEUE_URL: ${construct:jobs.queueUrl}
  consume:
    handler: Consume.consumer
    events:
      - sqs:
          arn: 
            Fn::GetAtt:
              - demo
              - Arn
          batchSize: 20
          maximumBatchingWindow: 200    
    

plugins:
  - serverless-lift
  - serverless-offline

resources: 
  Resources: 
    demo:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "demo"
    
    
    dlqlist: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-dlqlist-${sls:stage}
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
